Repository CSID-DGU/admin_be, pull requests merged in 2025-09, with the labels that each got.

#119 [feat] #118 Add port request table
  src/main/java/DGU_AI_LAB/admin_be/domain/portRequests/entity/PortRequests.java
Labels: ✨ feature

#122 [fix] Modify unique constraints from PortRequests entity
  src/main/java/DGU_AI_LAB/admin_be/domain/portRequests/entity/PortRequests.java
Labels: 🐛 bug

#123 [feat/docs] Config 서버 API 연동 (우분투 계정 삭제) 및 API 명세서 작성
  src/main/java/DGU_AI_LAB/admin_be/domain/alarm/controller/docs/AlarmApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/containerImage/controller/docs/ContainerImageApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/dashboard/controller/docs/DashBoardApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/controller/GroupController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/controller/docs/GroupApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/dto/request/CreateGroupRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/pod/controller/docs/PodApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/AdminRequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/ConfigRequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/AcceptInfoApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/AdminRequestApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/ConfigRequestApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/RequestApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/ApproveRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/RejectRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/AcceptInfoResponseDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/Request.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/Status.java
  src/main/java/DGU_AI_LAB/admin_be/domain/resourceGroups/controller/docs/ResourceGroupApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/AdminUserController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/UserController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/docs/AdminUserApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/docs/AuthApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/docs/EmailApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/docs/UserApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/request/PasswordUpdateRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/request/PhoneUpdateRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/AdminUserService.java
Labels: 📚 docs, ✨ feature, ♻️ refactor

#125 [feat] 사용 변경 신청 및 관리자 승인/거절, 그룹 생성
  src/main/java/DGU_AI_LAB/admin_be/domain/dashboard/controller/DashboardController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/controller/GroupController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/controller/docs/GroupApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/dto/request/CreateGroupRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/repository/GroupRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/service/GroupService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/AdminRequestChangeController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/AdminRequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/RequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/AdminRequestApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/AdminRequestChangeApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/ApproveModificationDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/ModifyRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/RejectModificationDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/RejectRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/UserGroupUpdateRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/ChangeType.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/Request.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/repository/RequestRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/ConfigRequestService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/usedIds/repository/UsedIdRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/usedIds/service/IdAllocationService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/docs/AdminUserApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/docs/UserApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/AdminUserService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/UserService.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
  src/main/java/DGU_AI_LAB/admin_be/global/config/WebClientConfig.java
Labels: ✨ feature

#127 [deploy] develop -> main
  src/main/java/DGU_AI_LAB/admin_be/domain/dashboard/controller/DashboardController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/controller/GroupController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/controller/docs/GroupApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/dto/request/CreateGroupRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/repository/GroupRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/service/GroupService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/AdminRequestChangeController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/AdminRequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/RequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/AdminRequestApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/AdminRequestChangeApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/ApproveModificationDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/ModifyRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/RejectModificationDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/RejectRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/UserGroupUpdateRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/ChangeType.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/Request.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/repository/RequestRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/ConfigRequestService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/usedIds/repository/UsedIdRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/usedIds/service/IdAllocationService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/docs/AdminUserApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/docs/UserApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/AdminUserService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/UserService.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
  src/main/java/DGU_AI_LAB/admin_be/global/config/WebClientConfig.java
Labels: 🚧deploy

#132 [feat] #131 additional port input added
  src/main/java/DGU_AI_LAB/admin_be/domain/portRequests/entity/PortRequests.java
  src/main/java/DGU_AI_LAB/admin_be/domain/portRequests/repository/PortRequestRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/portRequests/service/PortRequestService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/ApproveRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/PortRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/SaveRequestRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/PortMappingDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/SaveRequestResponseDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/Request.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
Labels: ✨ feature

#136 [feat] farm/lab 서버 구분하여 알림 전송하는 서비스 구현
  src/main/java/DGU_AI_LAB/admin_be/domain/alarm/service/AlarmService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestCommandService.java
Labels: ✨ feature

#133 [feat/docs] 사용 변경 신청 승인 pvc 호출 및 문서 보완
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/AdminRequestChangeController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/RequestApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestCommandService.java
Labels: 📚 docs, ✨ feature

#139 [deploy] develop -> main
  src/main/java/DGU_AI_LAB/admin_be/domain/alarm/service/AlarmService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/portRequests/entity/PortRequests.java
  src/main/java/DGU_AI_LAB/admin_be/domain/portRequests/repository/PortRequestRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/portRequests/service/PortRequestService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/AdminRequestChangeController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/RequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/RequestApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/ApproveRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/PortRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/SaveRequestRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/PortMappingDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/SaveRequestResponseDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/Request.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/repository/RequestRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/request/UserLoginRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
Labels: 🚧deploy
