Repository CSID-DGU/admin_be, pull requests merged in 2025-08, with the labels that each got.

#62 [feat] 회원가입 필드 추가
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/request/UserRegisterRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/entity/User.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/UserLoginService.java
Labels: ✨ feature

#69 [fix] 회원가입 시 필드 수정 및 UID & GID 관련 코드 삭제
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/AdminUserController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/request/UserRegisterRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/response/UserSummaryDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/entity/User.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/repository/UserRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/UserLoginService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/UserService.java
Labels: 🐛 bug

#70 [deploy] 회원가입 수정용 배포
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/AdminUserController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/request/UserRegisterRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/response/UserSummaryDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/entity/User.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/repository/UserRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/UserLoginService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/UserService.java
Labels: 🐛 bug

#72 [feat] 사용자 정보 변경 API 개발
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/UserController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/request/PasswordUpdateRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/request/PhoneUpdateRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/entity/User.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/UserService.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
Labels: ✨ feature

#90 [feat] 유저 그룹 반환 API
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/controller/GroupController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/dto/response/GroupResponseDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/service/GroupService.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
Labels: ✨ feature

#99 [fix] #93 Edit user dashboard API & Add response data for admin request management pannel
  dummy_data.sql
  src/main/java/DGU_AI_LAB/admin_be/domain/dashboard/controller/DashboardController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/dashboard/service/DashboardService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/SaveRequestResponseDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/UserServerResponseDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/Status.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestService.java
Labels: ✨ feature

#101 [feat/fix] 그룹 생성 API, 우분투 그룹 관련 버그 수정
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/controller/GroupController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/dto/request/CreateGroupRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/entity/Group.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/repository/GroupRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/groups/service/GroupService.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
  src/main/java/DGU_AI_LAB/admin_be/global/auth/SecurityWhitelist.java
Labels: 🐛 bug, ✨ feature

#103 [refactor] 사용 신청 username 예외 처리, ssh 로그인 경로 수정
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/controller/AuthController.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
Labels: ♻️ refactor

#109 [fix/refactor] 사용 신청 생성 서비스 로직 수정
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/SaveRequestRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/usedIds/service/IdAllocationService.java
Labels: 🐛 bug, ♻️ refactor

#116 [feat] 관리자가 사용 신청 승인 시 pvc 호출 로직 추가
  build.gradle
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/PvcRequest.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/PvcRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
  src/main/java/DGU_AI_LAB/admin_be/global/config/RestTemplateConfig.java
  src/main/java/DGU_AI_LAB/admin_be/global/config/WebClientConfig.java
Labels: ✨ feature

#117 [deploy] develop -> main
  build.gradle
  src/main/java/DGU_AI_LAB/admin_be/domain/alarm/controller/AlarmController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/alarm/service/AlarmService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/containerImage/repository/ContainerImageRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/containerImage/service/ContainerImageService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/dashboard/controller/DashboardController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/dashboard/controller/docs/DashBoardApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/pod/controller/PodController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/AcceptInfoController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/AdminRequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/ConfigRequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/RequestController.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/AcceptInfoApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/AdminRequestApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/controller/docs/RequestApi.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/ApproveModificationDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/ModifyRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/PvcRequest.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/request/PvcRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/AcceptInfoResponseDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/ChangeRequestResponseDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/dto/response/SaveRequestResponseDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/ChangeRequest.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/ChangeType.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/Request.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/entity/RequestGroupId.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/repository/ChangeRequestRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/repository/RequestRepository.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/AdminRequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/ConfigRequestService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestCommandService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestQueryService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/requests/service/RequestService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/resourceGroupImages/entity/ResourceGroupImageId.java
  src/main/java/DGU_AI_LAB/admin_be/domain/resourceGroups/service/ResourceGroupService.java
  src/main/java/DGU_AI_LAB/admin_be/domain/usedIds/entity/UsedId.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/request/PasswordUpdateRequestDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/dto/response/UserSummaryDTO.java
  src/main/java/DGU_AI_LAB/admin_be/domain/users/service/UserService.java
  src/main/java/DGU_AI_LAB/admin_be/error/ErrorCode.java
  src/main/java/DGU_AI_LAB/admin_be/global/config/RestTemplateConfig.java
  src/main/java/DGU_AI_LAB/admin_be/global/config/WebClientConfig.java
Labels: 🚧deploy
